myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path("admin/", admin.site.urls),
	path("", include("blog.urls")),
]

myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("detail/<int:pk>", views.Detail.as_view(), name='detail'),
    path("write/", views.Write.as_view(), name='write'),
    path("",views.get, name='list')
]

myapp/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField() 
    writer = models.CharField(max_length=10)
    
class ListView(models.Model):
    model = Post
    template_name = 'blog/post_list.html' #템플릿
    context_object_name = 'posts' #변수 값의 이름

myapp/blog/forms.py
#blog/forms.py
from django import forms
from .models import Post

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']
        

myapp/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import Post
from django.views.generic import ListView, CreateView, DetailView
from .forms import PostForm
from django.urls import reverse_lazy

def get(request):
    post_objs = Post.objects.all()
    context = {
        "posts": post_objs
    }
    return render(request, 'blog/post_list.html', context)

class Detail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    
class Write(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:list')

myapp/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>블로그</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

myapp/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>제목: {{ post.title }}</h2>
<p>내용: {{ post.content }}</p>
<a href="{% url 'blog:list' %}" class="btn btn-outline-success"><input type="button" value="목록으로"></a>
{% endblock %}

myapp/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>블로그 글 작성 화면</h1>
    <form action="{%url 'blog:write'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

myapp/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>블로그 게시판 화면</h1>
    <a href="{% url 'blog:write' %}" class="btn btn-outline-success"><input type="submit" value="글 작성"></a>
    <ul>
    {% for post in posts %}
        <a href="{% url 'blog:detail' pk=post.pk %}"><li>{{post.title}}</li></a>
    {% endfor %}
    </ul>
{% endblock %}